for INPUT_FILE in wmt18model1.nonsense.results wmt18model2.nonsense.results wmt16model.nonsense.results wmt14convmodel.nonsense.results; do
    export CUDA_VISIBLE_DEVICES=0; python adversarial_evaluate.py wmt18trans/wmt18ensemble/ --arch transformer_vaswani_wmt_en_de_big --source-lang en --target-lang de --restore-file wmt18trans/wmt18ensemble/wmt18.model1.pt  --valid-subset test --bpe subword_nmt --bpe-codes wmt18trans/wmt18ensemble/code --no-check-resegmentation --malicious-nonsense < $INPUT_FILE > wmt18model1.transfer_from.$INPUT_FILE
    export CUDA_VISIBLE_DEVICES=0; python adversarial_evaluate.py wmt18trans/wmt18ensemble/ --arch transformer_vaswani_wmt_en_de_big --source-lang en --target-lang de --restore-file wmt18trans/wmt18ensemble/wmt18.model2.pt  --valid-subset test --bpe subword_nmt --bpe-codes wmt18trans/wmt18ensemble/code --no-check-resegmentation --malicious-nonsense  < $INPUT_FILE > wmt18model2.transfer_from.$INPUT_FILE
    export CUDA_VISIBLE_DEVICES=0; python adversarial_evaluate.py wmt16trans/wmt16.en-de.joined-dict.newstest2014/ --arch transformer_vaswani_wmt_en_de_big --restore-file wmt16trans/wmt16.en-de.joined-dict.transformer/model.pt  --valid-subset test --bpe subword_nmt --bpe-codes wmt16trans/wmt16.en-de.joined-dict.transformer/bpecodes --no-check-resegmentation --malicious-nonsense < $INPUT_FILE > wmt16model1.transfer_from.$INPUT_FILE
    export CUDA_VISIBLE_DEVICES=0; python adversarial_evaluate.py wmt14conv/wmt14.en-de.newstest2014/ --source-lang en --target-lang de --arch fconv_wmt_en_de --restore-file wmt14conv/wmt14.en-de.fconv-py/model.pt --valid-subset test --bpe subword_nmt --bpe-codes wmt14conv/wmt14.en-de.fconv-py/bpecodes --no-check-resegmentation --malicious-nonsense < $INPUT_FILE > wmt18model1.transfer_from.$INPUT_FILE 
    #export CUDA_VISIBLE_DEVICES=0; python adversarial_evaluate.py wmt17conv/wmt14.en-de.newstest2014/ --source-lang en --target-lang de --arch fconv_wmt_en_de --restore-file wmt17conv/wmt14.en-de.fconv-py/model.pt --valid-subset test --bpe subword_nmt --bpe-codes wmt17conv/wmt14.en-de.fconv-py/bpecodes --no-check-resegmentation --malicious-nonsense < $INPUT_FILE > wmt18model1.transfer_from.$INPUT_FILE
    #export CUDA_VISIBLE_DEVICES=0; python dont_flip.py iwslttrans/iwslt14.tokenized.de-en/ --arch transformer_iwslt_de_en --restore-file iwslttrans/checkpoint_best.pt --valid-subset test --bpe subword_nmt --bpe-codes iwslttrans/iwslt14.tokenized.de-en/code --no-check-resegmentation --malicious-nonsense < $INPUT_FILE > iwsltmodel.transfer_from.$INPUT_FILE
   #export CUDA_VISIBLE_DEVICES=0; python dont_flip.py wmt18trans/wmt18ensemble/ --arch transformer_vaswani_wmt_en_de_big --source-lang en --target-lang de --restore-file wmt18trans/wmt18ensemble/wmt18.model3.pt  --valid-subset test --bpe subword_nmt --bpe-codes wmt18trans/wmt18ensemble/code --no-check-resegmentation --malicious-nonsense  < $INPUT_FILE > wmt18model3.transfer_from.$INPUT_FILE
done
